/* Deterministic single-file release. Sources remain independently testable. */
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const root = path.resolve(__dirname, '..');

function build() {
  let html = fs.readFileSync(path.join(root, 'src/index.template.html'), 'utf8');
  const read = name => fs.readFileSync(path.join(root, name), 'utf8');
  const icon = fs.readFileSync(path.join(root, 'icon.svg')).toString('base64');
  html = html.replace(/href="icon.svg"/g, 'href="data:image/svg+xml;base64,' + icon + '"');
  html = html.replace(/<link rel="stylesheet" href="(assets\/[^"]+\.css)">/g,
    (_, name) => {
      const css = read(name);
      if (/<\/style/i.test(css) || /@import|url\(/i.test(css)) throw new Error('CSS must be self-contained: ' + name);
      return '<style data-source="' + name + '">\n' + css + '\n</style>';
    });
  const scripts = [];
  html = html.replace(/<script src="(assets\/[^"]+\.js)" defer><\/script>/g,
    (_, name) => {
      const js = read(name);
      new vm.Script(js, {filename: name});
      // Escape HTML raw-text terminators without changing JavaScript strings.
      scripts.push('<script data-source="' + name + '">\n' + js.replace(/<\/script/gi, match => '<\\/' + match.slice(2)) + '\n</script>');
      return '';
    });
  if (scripts.length !== 4) throw new Error('Expected all four application scripts');
  // Inline classic scripts do not support defer. Run after the DOM is parsed,
  // before DOMContentLoaded, preserving global scope and source execution order.
  html = html.replace('</body>', scripts.join('\n') + '\n</body>');
  if (/(?:src|href)="assets\//.test(html)) throw new Error('Unbundled asset reference');
  return html.replace('<!DOCTYPE html>', '<!DOCTYPE html>\n<!-- Generated by npm run build; edit src/index.template.html and assets instead. -->');
}

if (require.main === module) {
  const output = build(), target = path.join(root, 'index.html');
  const billingTarget = path.join(root, 'server/Billing.gs');
  const billingSource = '// Generated from assets/billing.js by npm run build. Do not edit.\n' + fs.readFileSync(path.join(root, 'assets/billing.js'), 'utf8');
  if (process.argv.includes('--check')) {
    if (fs.readFileSync(target, 'utf8') !== output) throw new Error('index.html is stale: run npm run build');
    if (fs.readFileSync(billingTarget, 'utf8') !== billingSource) throw new Error('server/Billing.gs is stale: run npm run build');
    console.log('Single-file output matches sources');
  } else {
    fs.writeFileSync(target, output);
    fs.writeFileSync(billingTarget, billingSource);
    console.log('Built index.html (' + Buffer.byteLength(output) + ' bytes)');
  }
}
module.exports = {build};
